dzb_rentacar:
    resource: "@DzbRentacarBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

homepage:
    pattern: /
    default: {_controller: DzbRentacarBundle:Reservation:index}

DzbRentacarBundle:
    resource: "@DzbRentacarBundle/Controller/"
    type: annotation
    prefix: /